import { createClient } from "@supabase/supabase-js";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: Request) {
  try {
    const { name, email, subject, message } = await req.json();

    if (!name || !email || !message) {
      return Response.json({ success: false, error: "Name, email, and message are required." }, { status: 400 });
    }

    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );

    // Save inquiry to DB
    await supabase.from("contact_inquiries").insert({
      name,
      email,
      subject: subject || "General Inquiry",
      message,
      status: "new",
    });

    if (process.env.RESEND_API_KEY?.startsWith("re_")) {
      // 1. Send notification to team
      await resend.emails.send({
        from: "Axelo CRM <concierge@axelotours.co.ke>",
        to: "concierge@axelotours.co.ke",
        subject: `New Contact Inquiry: ${subject || "General Inquiry"}`,
        html: `
          <div style="font-family: sans-serif; color: #333; max-width: 600px;">
            <h2 style="color: #1a1a1a;">New Inquiry from ${name}</h2>
            <table style="width:100%; border-collapse: collapse; font-size: 14px;">
              <tr><td style="padding: 8px 0; font-weight:bold; width:120px;">From:</td><td>${name} &lt;${email}&gt;</td></tr>
              <tr><td style="padding: 8px 0; font-weight:bold;">Subject:</td><td>${subject || "General Inquiry"}</td></tr>
            </table>
            <div style="margin-top: 20px; padding: 20px; background: #f9f9f9; border-radius: 12px;">
              <p style="margin:0; white-space: pre-wrap;">${message}</p>
            </div>
            <p style="margin-top: 24px; font-size: 12px; color: #888;">Auto-generated by Axelo Tours CRM</p>
          </div>
        `,
      });

      // 2. Send confirmation to customer
      await resend.emails.send({
        from: "Axelo Tours <concierge@axelotours.co.ke>",
        to: email,
        subject: "We received your message — Axelo Tours",
        html: `
          <div style="font-family: sans-serif; color: #333; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #1a1a1a;">Hi ${name},</h2>
            <p>Thank you for reaching out to <strong>Axelo Tours & Safari Ltd.</strong></p>
            <p>We received your message and our team will get back to you at <strong>${email}</strong> within <strong>2 hours</strong>.</p>
            <div style="margin: 24px 0; padding: 20px; background: #fdf6e3; border-left: 4px solid #e5a93e; border-radius: 8px;">
              <p style="margin: 0; font-size: 13px; color: #7a6a3c;"><strong>Your message:</strong><br/><br/>${message}</p>
            </div>
            <p>In the meantime, feel free to explore our safari packages at <a href="https://axelotours.co.ke/safaris" style="color:#e5a93e">axelotours.co.ke</a>.</p>
            <p>Best regards,<br/><strong>The Axelo Tours Team</strong></p>
          </div>
        `,
      });
    }

    return Response.json({ success: true });
  } catch (err: any) {
    console.error("Contact form error:", err);
    return Response.json({ success: false, error: err.message }, { status: 500 });
  }
}
